# Site settings
title: Niousha's site
email: nioushajafari@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  NJ's dope ass life in a site
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: niousha75
github_username:  nioushajafari

# Build settings
markdown: kramdown
